
trigger:
- master

# strategy:
#   matrix:
#     linux:
#       operatingSystem: 'ubuntu-latest'
#     mac:
#       operatingSystem: 'macos-latest'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Buildjob
    steps:
    - bash: echo Do build job 
- stage: DevDeploy
  jobs:
  - deployment: DevDeployJob
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
            - bash: echo deploy to dev
- stage: QADeploy
  jobs:
  - deployment: QADeployJob
    environment: QA
    strategy:
     runOnce:
       deploy:
         steps:
           - bash: echo deploy to QA
          


# steps:
# - script: echo Running on ubuntu-latest
#   displayName: 'Run a one-line script'
