trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, aws-with terraform!
  displayName: 'Run a one-line script'

- task: TerraformTaskV1@0
  inputs:
    provider: 'aws'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/aws/Kubernetes'
    backendServiceAWS: 'aws-for-terraform'
    backendAWSBucketName: 'aws-s3-terraform-state-prdevops-xyz'
    backendAWSKey: 'k8s-dev.tfstate'