
trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:

# Build
  #Build docker image
  # Push the docker image : 100 (tag)  -> this is an image with tag
  # copy files(deployment.yaml) to staging directory
  # publish artifacts (deployment.yaml)

- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'prdevops-docker-hub'
        repository: 'prdevops/currency-exchange-devops'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
  
    - task: CopyFiles@2
      inputs:
         SourceFolder: '$(System.DefaultWorkingDirectory)'
         Contents: '**/*.yaml'
         TargetFolder: '$(Build.ArtifactStagingDirectory)'
       
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'manifests'
        publishLocation: 'Container'

#Deploy
  # Download the artifacts
  #  image:100(tag) is deployed on k8s cluster
  # apply kubectl apply -f deployment.yaml 
	# this file is in #configuration->kubernetes>deployment.yaml ##

- stage: Deploy
  displayName: Deploy image
  jobs:  
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: 'manifests'
          itemPattern: '**/*.yaml'
          targetPath: '$(System.ArtifactsDirectory)'
      - task: KubernetesManifest@0
        inputs:
          action: 'deploy'
          kubernetesServiceConnection: 'aws-kubernetes-cluster-service-connection'
          namespace: 'default'
          manifests: '$(System.ArtifactsDirectory)/configuration/kubernetes/deployment.yaml'
          containers: prdevops/currency-exchange-devops:$(tag)
      